version: '3'

services:
  wcagger:
    container_name: wcagger
    build:
      context: .
      dockerfile: ./config/Dockerfile
    restart: always
    volumes:
      - ./nuxt:/app
      - node_modules:/app/node_modules
    hostname: client
    ports:
      - "1270:3000"
    networks:
      - wcagger

volumes:
  node_modules:

networks:
  wcagger:
    name: wcagger
